### ISSUE TITLE
FE  - Light/Dark mode cannot detect user's settings

### ISSUE THREAD

**Issue by marcelluscaio** [bluewave-labs/bluewave-uptime#1026]
**Describe the bug**
 Light/Dark mode cannot detect user's settings

**To Reproduce**
Change system and browser settings to Dark, and access the project. You will see that the it defaults to light.

**Expected behavior**
Page should detect user's settings for light/dark mode.

**Additional context**
I believe we could follow a native approach using prefers-color-scheme's media query

**Comment by gorkem-bwl** [comment]
Yep, let's do this one. Setting the label as "good-first-issue" as it's relatively an easy feature for contributors.

**Comment by aarya-16** [comment]
@marcelluscaio I've looked at it and seen what needs to be done. Can I work on this ?

**Comment by marcelluscaio** [comment]
Yes, @aarya-16 ! Thank you for your interest

**Comment by aarya-16** [comment]
@marcelluscaio I have made PR #1072 addressing this issue.

**Comment by marcelluscaio** [comment]
Thanks for your contribution, @aarya-16 . I will check it out
