### ISSUE TITLE
FE - Modal dismiss does not prevent clicks outside

### ISSUE THREAD

**Issue by marcelluscaio** [bluewave-labs/bluewave-uptime#1027]
**Describe the bug**
When clicking on remove monitor, on the monitor page, a modal opens. If you cancel it by clicking outside of the modal, it navigates to another page.

**To Reproduce**
1. Go to the monitors page
2. Click on the gear icon, and then remove monitor
3. A modal will open
4. Click outside of the modal
5. It should just close the modal, but it navigates to another page

**Expected behavior**
It should just close the modal

**Comment by navishmonga** [comment]
Can I work on this issue ?

**Comment by gorkem-bwl** [comment]
Yes please, go ahead. Make sure you adhere our coding standards, and reuse code if that is implented previously elsewhere.

**Comment by navishmonga** [comment]
When I click outside the modal it closes , but when i click anywhere inside the modal (other than cancel and delete button) , it takes me to monitor details of the monitor I want to delete.

**Comment by navishmonga** [comment]
https://github.com/user-attachments/assets/c546f249-1ee5-46fb-88dd-5bfc2ab9bdc4

Please check this out

**Comment by gorkem-bwl** [comment]
That's right. You can go ahead.

**Comment by navishmonga** [comment]
In the issue it is mentioned that it redirects when clicked outside the modal, but it is not happening for me , rather, for me it is happening when i click inside the modal, So should i configure the modal that it should not change even when clicked inside the modal ?

**Comment by gorkem-bwl** [comment]
That's right. It shouldn't change even when clicked inside the modal.
