### ISSUE TITLE
Remove Monitor table border 

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-uptime#1064]
Currently our monitor table looks like this: 

<img width="1385" alt="before" src="https://github.com/user-attachments/assets/026313bf-66b9-48ec-be69-02e8aea20f87">

The border is redundant and should be removed. After the fix it should look like this: 

<img width="1461" alt="after" src="https://github.com/user-attachments/assets/4ae51fda-2501-41ee-b0c5-7e45072d3be5">

**Comment by ketansahugit** [comment]
Hey, I'm working on this.

**Comment by navishmonga** [comment]
Can I work on this issue ?
