### ISSUE TITLE
FE - Hardware Monitoring - Create Hardware Monitor

### ISSUE THREAD

**Issue by ajhollid** [bluewave-labs/bluewave-uptime#1067]
There should be a create hardware monitor page, similar to other create monitor pages.

- [ ] It should follow the [figma designs](https://www.figma.com/design/RPSfaw66HjzSwzntKcgDUV/Uptime?node-id=0-1&node-type=canvas&t=gbgpwQFlKcXClSrl-0)
- [ ] Include full user input validation
  - [ ] Validation can be handled in `onBlur` and on form submission

![Screenshot from 2024-10-25 10-04-51](https://github.com/user-attachments/assets/d921dc84-d780-4226-95a4-91ec373cb1c4)

**Comment by jennifer-gan** [comment]
Is the server url a text field with a placeholder, such as "https:// " ?

**Comment by gorkem-bwl** [comment]
The design now includes "Authorization secret", fyi @jennifer-gan @ajhollid 

<img width="936" alt="image" src="https://github.com/user-attachments/assets/24ad9833-1bbf-4e1f-8c2a-4a41da0ce545">
