### ISSUE TITLE
FE - Hardware Monitoring - Line Graph

### ISSUE THREAD

**Issue by ajhollid** [bluewave-labs/bluewave-uptime#1069]
There should be a reusable graph component for Hardware Monitors

- [ ] It should display time on the x axis
- [ ] It should display an arbitrary unit on the y axis
- [ ] It should be responsive
- [ ] It should use the [Recharts library](https://recharts.org/en-US/) as we use that for charting already

**Comment by ofaruk84** [comment]
Working on this !

**Comment by gorkem-bwl** [comment]
Hi @ofaruk84 - go ahead. Please check the look & feel, and general design of the graph component we use throughout the platform. If there is a relevant component, you can also use it.

**Comment by ofaruk84** [comment]
Hey @gorkem-bwl  @ajhollid  ,

Implementation PR: https://github.com/bluewave-labs/bluewave-uptime/pull/1077

Thanks!

**Comment by gorkem-bwl** [comment]
Thanks Faruk. We need to sync the design with the chart under Page Insights. Can you ensure the styling, look & feel of your charts is the same as the one under Page Insights? (e.g background lines, colors, mouse over effects etc).

**Comment by ofaruk84** [comment]
> Thanks Faruk. We need to sync the design with the chart under Page Insights. Can you ensure the styling, look & feel of your charts is the same as the one under Page Insights? (e.g background lines, colors, mouse over effects etc).

For just clearence, do you mean Figma designs ? Cause I could not found Page Insights in any directory.

**Comment by gorkem-bwl** [comment]
Sure, let me explain. By page insights (slightly off the name) I meant "Pagespeed monitoring" which you can find here: https://bluewavelabs.gitbook.io/uptime-manager/users-guide/pagespeed-monitoring

When you install BlueWave Uptime on localhost and add a site, you can examine how it looks like. 

Hope it is a bit more clear now?

**Comment by ajhollid** [comment]
Hi @ofaruk84 ,

Thanks for your contribution here!

We have pretty specific design guidelines to follow for this issue.

Please see the existing MonitorDetailsAreaGraph to see what a line chart for our application should look like.

The component for this issue and that component are very similar and probably should in fact be refactored to either be the same component, or have a base components that each individual chart will then extend.
