### ISSUE TITLE
NPM Dependency Versions

### ISSUE THREAD

**Issue by ajhollid** [bluewave-labs/bluewave-uptime#109]
How does everyone feel about locking in depenency versions for the libaries that we are using?

Right now I see that we're using the npm default which is to update all packages to minor version changes whenever dependencies are installed. 

It's been my experience that NPM packages often have breaking changes even in minor versions, so if we have a working config it might be nice to lock it in.

We can update the `package.json` files to use exact versions just by removing the caret `^` before the dependency.

`"dotenv": "^16.4.5"`  => `"dotenv": "16.4.5"`

We can also avoid the issue by telling NPM to use exact versions in the future:

`npm install dotenv --save-exact`

It's a minor thing, but I've been burned here before.  As they are "minor" version changes too the build often still works too, which makes breaking changes even more difficult to find.

**Comment by Skorpios604** [comment]
I see what you mean, and you make a good point about the potential for breaking changes in minor version updates. My main concern with locking dependencies is that maybe it could lead to missing out on important update like security patches and performance improvements. 

In that case would we just need to manually update dependencies?

**Comment by ajhollid** [comment]
That's also a really good point, we would have to be a bit more vigilant about what's going on with those packages.  

We could think about running `npm audit` during our build process to make sure that we don't have any major vulnerabilities in our app.  That would be something we could do as well as running tests during build.

Food for thought!

**Comment by Skorpios604** [comment]
Yeah for sure. `npm audit` is a good one.
