### ISSUE TITLE
Loading spinners and Results field

### ISSUE THREAD

**Issue by ajhollid** [bluewave-labs/bluewave-uptime#116]
We need some progress spinners and general error fields for components that will make backend requests

The progress spinner should:
1.  Show progress when requesting data from backaned
2.  Stop showing progress when operation is complete, in either error or success form

Results field should:

1.  Show success/error message returned from the bakend on operation complete

Maybe a toast is a nice fromat for the response message? [This might be worth checking out](https://www.npmjs.com/package/react-toastify)

**Comment by Skorpios604** [comment]
Excellent idea! And whooooa😮‍💨! Those look super sleek and modern

**Comment by ajhollid** [comment]
Yeah they look pretty nice!  If you or @MuhammadKhalilzadeh want to tackle adding these features to the project I can hanlde hooking them up to the redux state :+1:

**Comment by Skorpios604** [comment]
Ya for sure I can look into it
