### ISSUE TITLE
When there is a signed up admin user, do not show "Don't have an account? — Sign Up" section

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-uptime#1180]
The BlueWave Uptime system assumes the creation of at least one admin account, with the username and password configured immediately after setup. Once an admin account is established in MongoDB, the main dashboard should no longer display the "Don't have an account? — Sign Up" link at the bottom. Although this link becomes non-functional after the admin account is set up, its presence may cause confusion for the end user.

Here is a screenshot: 

<img width="845" alt="image" src="https://github.com/user-attachments/assets/007a2440-0b8c-4f3f-883f-2cb7c5870ad7">

**Comment by DemonicQuasar** [comment]
Hello, I'd like to contribute to this issue please.

**Comment by gorkem-bwl** [comment]
Sure, go ahead. Before sending a PR please write here how you are going to implement it.

**Comment by ajhollid** [comment]
@DemonicQuasar thanks for your proposal!  l I believe this link can just simply be removed however, I don't believe there is a situation where you can get to the login page when an admin account does not exist.

If the admin account doesn't exist you are redirected to the `/register` page.  

If it does exist, you shouldn't be prompted to sign up.

So I think this link can just be removed entirely, it's likely left over from an earlier implementation of the app from before the admin account flow was introduced.

@gorkem-bwl can you confirm?

**Comment by gorkem-bwl** [comment]
Yes, you are right. We already have this in place: `If the admin account doesn't exist you are redirected to the /register page.`

**Comment by ajhollid** [comment]
@DemonicQuasar sounds like it's going to be an easy fix then, just remove the link entirely! Thanks for your help here 👌

**Comment by DemonicQuasar** [comment]
Done, made a pull request after just removing that entirely, thanks everyone for the help.

**Comment by LonguCodes** [comment]
@ajhollid This issue should not be closed, as the PR closing the issue removed the button totally.

Currently, there is no ability to create a user during first setup.

The button should be removed conditionally, not just teleted from the code
