### ISSUE TITLE
Add a skeleton page to Infrastructure monitoring > Details page

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-uptime#1187]
When a user clicks on a server detail on the Monitoring page, a skeleton loader is displayed initially, followed by the full page content. We need to implement a similar approach on the Infrastructure Monitoring page. When a user accesses the server details (infra monitoring), a skeleton loader should appear before the content is loaded.

The most efficient way to achieve this is by replicating the implementation from the `Monitor > Details` page.

This is due 2.0 so needs to be taken care of in a few days or so.

**Comment by gorkem-bwl** [comment]
Sample design: https://www.figma.com/design/RPSfaw66HjzSwzntKcgDUV/Uptime?node-id=3469-4078&t=fujsXxXxdWyEQitY-1

<img width="919" alt="image" src="https://github.com/user-attachments/assets/4618e771-cff0-44b9-898f-4bbc7de773aa">

**Comment by ajhollid** [comment]
Hi @DemonicQuasar, there's actually a PR open for this issue already, but thanks for the offer to help!

If you'd like you can review the PR, we always appreciate PR reviews!
