### ISSUE TITLE
Up-down-paused sections should be stretched according to the browser width

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-uptime#174]
Please see the upper 3 blocks in this screenshot.

<img width="1408" alt="Screenshot 2024-06-21 at 5 32 59 PM" src="https://github.com/bluewave-labs/bluewave-uptime/assets/167266851/5d7d4a7a-44f1-4a7e-b2ac-44fe193f6a31">

**Comment by MuhammadKhalilzadeh** [comment]
Done
