### ISSUE TITLE
Frontend - Fix login and register styles

### ISSUE THREAD

**Issue by ajhollid** [bluewave-labs/bluewave-uptime#182]
Login and Register styles are broken after refactoring the root layout.

Likely just need a container to sort out the flex issues

**Comment by ajhollid** [comment]
It appears actually all that needs to be done here is remove the `width: 100vw` tag:

```
.login-page {
  width: var(--env-var-width-1);
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: var(--env-var-height-1);
}
```

to

```
.login-page {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: var(--env-var-height-1);
}
```

appears to resolve this issue.

**Comment by danielcj2** [comment]
Either that or, adding a parent class to this css selector in `Pages/Settings/index.css`.

`[class$="-form"] {
  width: inherit;
}`

to

`.settings [class$="-form"] {
  width: inherit;
}`

I can fix it on my end and add it along with my next PR.

**Comment by ajhollid** [comment]
> Either that or, adding a parent class to this css selector in `Pages/Settings/index.css`.
> 
> `[class$="-form"] { width: inherit; }`
> 
> to
> 
> `.settings [class$="-form"] { width: inherit; }`
> 
> I can fix it on my end and add it along with my next PR.

@danielcj2 this issue is related to the login/regsiter pages, I haven't noticed issues in the Settings page, I think we're all good there?

**Comment by danielcj2** [comment]
@ajhollid `[class$="form"]` will target elements whose class attribute ends with the string `-form`. In the login/register pages there's two classes wrapping the forms, `login-form` and `register-form` so it will target them as well. Easy fix, just need to add a parent to the selector so it only targets elements inside .settings page.

**Comment by ajhollid** [comment]
Sounds like a plan, thanks for the walkthrough, assigned to you!
