### ISSUE TITLE
Front End - Good First issue

### ISSUE THREAD

**Issue by danielcj2** [bluewave-labs/bluewave-uptime#193]
The password input field styling appears to be broken.

![image](https://github.com/bluewave-labs/bluewave-uptime/assets/122758391/42b90b43-a4c2-4a4c-9f6d-7cbc5f7cb656)

**Comment by faizan-o** [comment]
I Can Fix The Styling If You Please Assign The Issue To Me.

**Comment by ajhollid** [comment]
> I Can Fix The Styling If You Please Assign The Issue To Me.

Hi @faizan-o, if you'd like to work on this you can fork the repo and make a pull request with your changes.  We will review your PR once it is made :+1:
