### ISSUE TITLE
Implement buttons, avatar, switch toggles, checkboxes, button groups, tables, date picker, placeholder, progress, tabs and sectional groups with MUI

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-uptime#2]
<img width="5470" alt="Erdem" src="https://github.com/bluewave-labs/bluewave-uptime/assets/167266851/edd3528c-d4de-4975-be21-5209bfe1ad41">

**Comment by gorkem-bwl** [comment]
@popnfresh234 assigned to you. FYI.

**Comment by popnfresh234** [comment]
@gorkem-bwl received, thank you

**Comment by veyselboybay** [comment]
It seems like the mentioned components are implemented already, closing the issue.
