### ISSUE TITLE
Inline editing of the company name

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-uptime#222]
When the edit icon is clicked, the user should be able to edit the company name “inline”.

A stroke around the company name appears and the cursor is placed at the end of the company name.

When the user changes the company name and presses enter, it should sync with the backend DB, without the need to press any button.

This is a good first issue for a new contributor like you to get your foot on the door.

<img width="942" alt="Screenshot 2024-06-27 at 7 05 58 PM" src="https://github.com/bluewave-labs/bluewave-uptime/assets/167266851/960cc689-fd49-4c42-8b34-57d9c13d8ec3">

**Comment by Mohit-3007** [comment]
hi @gorkem-bwl ,

I would like to do the same, kindly assign to me
