### ISSUE TITLE
Frontend - Update navBar user dropdown

### ISSUE THREAD

**Issue by danielcj2** [bluewave-labs/bluewave-uptime#224]
Update user dropdown as per the Figma design

![image](https://github.com/bluewave-labs/bluewave-uptime/assets/122758391/562168c9-aae3-4ecb-9ce2-d7701dba7b31)

- Add icons
- Update links
- Add navigation

**Comment by gorkem-bwl** [comment]
Link to Figma design: https://www.figma.com/design/RPSfaw66HjzSwzntKcgDUV/Uptime-Genie?node-id=0-1&t=WqOFv9jqNTFGItpL-1

**Comment by Mohit-3007** [comment]
Hi @danielcj2 ,

I would like to do the same, kindly assign to me
