### ISSUE TITLE
Login page text fields should be 34px high everwhere

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-uptime#227]

**Comment by MuhammadKhalilzadeh** [comment]
I've checked height for text fields for 34px multiple times, and I had to target built-in classes for that or set specific ids for them, but it seems their built-in classes are targeted wrongly while working on other parts.
I'll fix it as soon as I'm done with the backend

**Comment by MuhammadKhalilzadeh** [comment]
Oh, easier than I thought!
Done!

**Comment by gorkem-bwl** [comment]
If this is merged, can you close this issue?

**Comment by MuhammadKhalilzadeh** [comment]
No, please do not close this. We fixed it, but had to revert it, since we decided to apply each change only on its related branch, so I'm waiting for my current branch to be merged, then I'll switch back and fix it.

**Comment by ajhollid** [comment]
You can switch back to master and then check out a new branch and create a new PR for this, you don't have to wait for the other to be merged first

**Comment by MuhammadKhalilzadeh** [comment]
Done ✅
