### ISSUE TITLE
Add product logo

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-uptime#276]
The SVG logo goes to: 

- Login pages
- Dashboard page, on the top left-hand side

For the login page, size is 353x31
For the dashboard, size is 177x16

If the sizes don't seem right to you, please feel free to modify them.

![BlueWave Uptime](https://github.com/bluewave-labs/bluewave-uptime/assets/167266851/b1a3613d-040b-49f3-91b4-ce5eecf9792f)

**Comment by gorkem-bwl** [comment]
Previously added wrong logo, fixed.

**Comment by Skorpios604** [comment]
Looks neat! Nice colors.

**Comment by gorkem-bwl** [comment]
I am quite up with finding logos for 3 products, so I chose the easy & fast way lol.

**Comment by Skorpios604** [comment]
Lol yes! Just change the text and you are good to go!

**Comment by Skorpios604** [comment]
My brother hired a guy from fiver to do his logos and i think they gave him 5 options to choose from. They had some pretty neat designs and the price was very reasonable.

**Comment by Skorpios604** [comment]
Its one of those things that could really brand your product.

**Comment by gorkem-bwl** [comment]
That's something we'll definitely do.. Just aiming sharp for the MVP for now, and then there will be a time we can reconsider the logos as well.

**Comment by MuhammadKhalilzadeh** [comment]
@gorkem-bwl 
If I set the `width: 177px`, the default `height` given is `23.23px` and the Logo completely `fills` its holder's space, but if it set the `height: 16px` **manually** too, their will be **a significant white space around the logo** in that frame and **the logo will be smaller**.
My suggestion is to only set the width and let the height be on its default. What's your opinion on this?

**Comment by MuhammadKhalilzadeh** [comment]
When I only set the Width 177px


![Screenshot 2024-07-12 124426](https://github.com/user-attachments/assets/cbf1ad90-16d7-43f6-a169-e0b7d9f6c4f3)



When I set both Width 177px and height 16px


![Screenshot 2024-07-12 124445](https://github.com/user-attachments/assets/a3e4a943-431d-474d-bd74-858c6b42d259)

**Comment by gorkem-bwl** [comment]
Second one looks neat and tidy. Can you also left-align it with the left-menu icons below?

**Comment by gorkem-bwl** [comment]
Oh I read your previous comment later. I think "**My suggestion is to only set the width and let the height be on its default. What's your opinion on this?**" is good. But in this case it would look considerably big, right, like in the 1st image?

**Comment by MuhammadKhalilzadeh** [comment]
Great 👍🏻
Then let's go with the tidy one ✅

**Comment by MuhammadKhalilzadeh** [comment]
@gorkem-bwl The real width of the logo isn't 177px in the small one btw!

**Comment by gorkem-bwl** [comment]
Can you take a whole screenshot please? That way we can better decide.

**Comment by MuhammadKhalilzadeh** [comment]
![Screenshot (93)](https://github.com/user-attachments/assets/95235d79-d6e0-44c2-8361-711a82c6d9e8)

**Comment by gorkem-bwl** [comment]
Is it possible to change the width (177) so that the left and right white padding can be removed?

**Comment by MuhammadKhalilzadeh** [comment]
Yes. By not setting the width. Like this:

![Screenshot (94)](https://github.com/user-attachments/assets/fa8a10c3-08ce-493e-9634-f3288eacbb95)

**Comment by gorkem-bwl** [comment]
Ah ok. I definitely made a mistake about the width calculation. This is much better, thanks.

**Comment by gorkem-bwl** [comment]
Also can you fix the left alignment as well?

**Comment by MuhammadKhalilzadeh** [comment]
If the width and height both are manually set, I'm not sure what to do yet, but I'm sure we'll find a way, since I was playing with alignment attribute to fix this while talking to you, but eventually only removing the width fixed it!

**Comment by MuhammadKhalilzadeh** [comment]
Are you planning to change the dimensions?

**Comment by gorkem-bwl** [comment]
No, dimensions are good. If we can take care of the left alignment we are good.

**Comment by MuhammadKhalilzadeh** [comment]
I'll do my best to fix it.
But take note that the blank space around the small one isn't from padding nor margin. it gets automatically included inside the fixed (width, height) we set

**Comment by MuhammadKhalilzadeh** [comment]
Do you want me to keep what we have now?
And should I do the same on the Login page too?

**Comment by gorkem-bwl** [comment]
Yes, let's keep this one (in terms of width):

<img width="198" alt="Screenshot 2024-07-12 at 12 54 54 PM" src="https://github.com/user-attachments/assets/67f5b5b4-fbd2-4eae-8736-7b9ffb7f31c4">


But let's left align it with the menu icons under.

**Comment by MuhammadKhalilzadeh** [comment]
Sure 👍🏻

**Comment by MuhammadKhalilzadeh** [comment]
![Screenshot 2024-07-12 132854](https://github.com/user-attachments/assets/7c778a39-5223-4dde-9453-53c911d0b7cd)
Fixed I guess ☑️
What do you think>

**Comment by gorkem-bwl** [comment]
Perfetti!

**Comment by gorkem-bwl** [comment]
For the login page, I think you can set the height and then the width can be automatically set there.

**Comment by MuhammadKhalilzadeh** [comment]
Login page, with only `width 353px`

![Screenshot 2024-07-12 140629](https://github.com/user-attachments/assets/b2293747-91af-4479-9f7a-1dcbb819fce3)


Now with (`width 353px`, `height 31px`) and only `height 31px`:

![Screenshot 2024-07-12 140648](https://github.com/user-attachments/assets/5e4fb381-33d8-4f0a-8a74-51a4780dbd70)


Which one do you prefer?
Or you have other ideas?

**Comment by gorkem-bwl** [comment]
The first one looks good to me.

**Comment by MuhammadKhalilzadeh** [comment]
Then let's go with that ✅
