### ISSUE TITLE
Design - Email templates

### ISSUE THREAD

**Issue by ajhollid** [bluewave-labs/bluewave-uptime#282]
We need several email templates

* Recovery emails
* Monitor up/down alert emails
* Registration emails

Probably more that I can't think of at the moment

**Comment by ajhollid** [comment]
https://mjml.io/

This looks very interesting, might be worth looking into

**Comment by Skorpios604** [comment]
Ya very cool! Definitely a nice place to start.

**Comment by gorkem-bwl** [comment]
Can you let me know where I can start sending those basic templates? It would be easier for me to just add them to a Google Docs file, and then anyone can copy directly from there? @ajhollid

**Comment by gorkem-bwl** [comment]
OK it looks like I can generate them with the desktop app (https://mjmlio.github.io/mjml-app/), which made my life easier (as opposed to using a text editor). 

Here are the first 4 email templates (welcome, lost password, server down, server up): https://docs.google.com/document/d/1q4USwDRGeZG4OiXGNIOlAIdfA73FcqjTWDUrIW4cajY/edit

**Comment by ajhollid** [comment]
Awesome, thanks for putting that together!

**Comment by Skorpios604** [comment]
Ya looks awesome! I took a look at it. Thank you @gorkem-bwl

**Comment by ajhollid** [comment]
@MuhammadKhalilzadeh Ready to get these all set up?

**Comment by MuhammadKhalilzadeh** [comment]
I'm just ready to get it on, and crush this task's skull 🔥

![MikeTysonSeriousGIF (2)](https://github.com/user-attachments/assets/0f63e4cd-e5ab-44b1-ac5c-a046854ed56c)
