### ISSUE TITLE
Database Schema and Routes

### ISSUE THREAD

**Issue by popnfresh234** [bluewave-labs/bluewave-uptime#40]
It might be nice to descrie all the routes that we will need to implement for the backend?  

Example:

`/api/v1/monitors`
`/api/v1/montiors/{monitorId}`

If we have a (for the time being) complete list of routes we will know what endpoints to implement on the backend.

Similarly, it would be nice to have all the schema we'll need defined.  We have some so far,

```
User
Montior
Check
Alert
```

There may be a few more, it looks like each user can have a number of `status` pages, so that will likely need it's own schema to be defined.

**Comment by gorkem-bwl** [comment]
For the monitors, those are my take.

Each monitor type can be HTTP(s), Ping or Port. All requests are attached with an API key or a token.

**/getmonitors:** By default lists all the monitors on the user's account. If the ID is given, retrieve only that monitor. 
- Friendly monitor name
- Monitor ID
- URL
- Type (HTTP, Ping or Port)
- Port if HTTP or Port
- Current status (up or down)
- Uptime ratio
- Last N days up/down status for the graph
- Last N days response time status for the graph
- SSL certificate information 
- Interval in seconds/minutes

**/newmonitor:** Creates a new monitor, returns an ID.
- Friendly monitor name
- URL
- Type (HTTP, ping or port)
- Port if HTTP or port
- SSL certificate information
- Interval in seconds/minutes (10 seconds, 15 seconds, 30 seconds, 1 minute, 2 minutes, 3 minutes, 5 minutes, 10 minutes, 15 minutes, 30 minutes)

**/editmonitor:** Edits a monitor by ID. The type of a monitor cannot be changed (e.g change an HTTP monitor to a ping monitor)
- ID
- Friendly name
- URL
- Type is immutable
- Port if HTTP or port
- Interval in seconds/minutes

**/deletemonitor:** Deletes a monitor by ID. 
- ID

**/resetmonitor:** Deletes all past data and response time data. 
- ID

**Comment by popnfresh234** [comment]
Completed:

`POST /api/v1/monitors` - create a monitor
`POST /api/v1/monitors/delete/{monitorId}` - delete a monitor
`POST /api/v1/monitors/edit/{monitorId` - edit a monitor

TODO:
1.  Reset Montiors
