### ISSUE TITLE
Monitor Checks Sort Order

### ISSUE THREAD

**Issue by ajhollid** [bluewave-labs/bluewave-uptime#403]
![image](https://github.com/user-attachments/assets/ff3034cf-9b36-4acb-a2da-2bfb97bf5307)

I believe we would like the Graph to display as above left `(oldest) -> right (newest)`.

However the chart displays as `top (oldest) -> bottom (newest)` , but I believe we want this to display as `top (newest) -> bottom (oldest)` as in a last-in-first-out stack.

Can you confirm @gorkem-bwl ?

If that's the case we can manipulate the data to display this properly.

**Comment by gorkem-bwl** [comment]
Confirmed for top (newest), bottom (oldest).
