### ISSUE TITLE
Slight changes in dashboard

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-uptime#422]
1. The header: it's simplified now - the white header has gone.
2. Up/down/paused blocks have new heights - they are shorter.
3. Background color (#FCFCFD) should be reflected in the main app.

Figma location: https://www.figma.com/design/RPSfaw66HjzSwzntKcgDUV/Uptime?node-id=1-39213&t=IfIXE75UmKXFm4BI-1

Screenshot: 
<img width="1029" alt="Screenshot 2024-07-23 at 1 57 21 AM" src="https://github.com/user-attachments/assets/50f9b8f1-171e-4804-963a-4eacd7d8b820">

**Comment by MuhammadKhalilzadeh** [comment]
This is what it looks like at the moment, I've fetched the latest from the `upstream`.
I see that user's `Full name` isn't in its place. Are we having any specific idea for it?

![Screenshot 2024-07-23 124623](https://github.com/user-attachments/assets/a50d9123-3b5e-4302-8a97-5c4f0e864798)

**Comment by MuhammadKhalilzadeh** [comment]
Not a big deal, it's fine 👍🏻

**Comment by MuhammadKhalilzadeh** [comment]
@gorkem-bwl 

After testing ideas we talked about on our call, this is the solution with the lowest expense for us, or as we talked we'll need to change this page's layout and then think about what to do with the dropdown and place it somewhere nice looking.

The shadow is removed, and the same border style from `DashboardSidebar.jsx` is added to the `border-bottom` for the `AppBar.js`.

What do you suggest?

![Screenshot (99)](https://github.com/user-attachments/assets/3971bd79-5283-439c-9390-2cada03e9ab7)

**Comment by gorkem-bwl** [comment]
Let’s move with this one 👍 much cleaner compared to the previous design. Thanks!

**Comment by MuhammadKhalilzadeh** [comment]
@gorkem-bwl 
The header: it's simplified now - the white header has gone. ✅
Up/down/paused blocks have new heights - they are shorter. ✅
Background color (#FCFCFD) should be reflected in the main app. ✅

Final result.
Please check to see if this is what we want:

![Screenshot 2024-07-23 192514](https://github.com/user-attachments/assets/a9c33145-9f11-4f39-b3fa-2ecc4b126e46)

**Comment by gorkem-bwl** [comment]
Yes! This is way better in terms of looks. Thank you.
