### ISSUE TITLE
Button animations and button group sync

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-uptime#480]
@danielcj2 Do you think we can add some onmousehover actions to those buttons? Maybe rotating the svg icon by 360 degrees (e.g https://www.youtube.com/watch?v=17DmCGIdFbc), or adding a subtle, smooth-appearing background to the button itself? 

Another thing: The button groups on this page differ from those under the Incidents page. The ones on the Incidents page are better looking. Can we also change those as well? 

<img width="1718" alt="Screenshot 2024-07-30 at 9 18 02 AM" src="https://github.com/user-attachments/assets/45a90136-5d21-4805-a80f-c8f8b51b4a2c">

**Comment by danielcj2** [comment]
Will do 👍
