### ISSUE TITLE
FE - Monitor Sort Order

### ISSUE THREAD

**Issue by ajhollid** [bluewave-labs/bluewave-uptime#498]
Currently the monitors cannot be sorted:

![image](https://github.com/user-attachments/assets/faf16320-5238-48fd-90fa-0611622e1a29)

If we want to enable we can sort on either the client or the backend, with the usual tradeoffs.

**Client side**
- Downside: Potentially slow if many monitors
- Upside: No need for API call, easy to implement

**Server side** 
- Downside: Requires an API call, marginally more complicated to implement
- Upside: Client will not be blocked while waiting for data

**Comment by Skorpios604** [comment]
Seems like a good idea. Some people might want to sort by which monitors are up or down. Like where that arrow is next to status. Users might intuitively click that thinking that it will sort the monitors for them. It is a very wide spread feature.

**Comment by gorkem-bwl** [comment]
My take: let's go with the client side and if things got slow with hundreds of servers, we can easily switch (I hope that happens lol). Eventually we'll add filters on top of the table, helping users to view only the up or down monitors

**Comment by gorkem-bwl** [comment]
Another take: The incidents page consists of more than 2500 entries and client side filtering seems to be fast enough. I am not in a position to compare the amount of data on the table (dashboard) and the table (incidents) but I tend to believe it shouldn't be an issue to go client side here.

**Comment by ajhollid** [comment]
Alright! Let's do it client side and see how it works, always possible to change later if performance degrades.
