### ISSUE TITLE
Check if endpoint URL resolves before adding the monitor

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-uptime#513]
When adding a monitor, the endpoint must be checked to move forward with adding.

If the endpoint URL doesn't resolve, it should throw a notification saying that the endpoint doesn't resolve. During the endpoint checking process, the "Create new monitor" button should read "Checking the endpoint". 

There are two options: 

1. If the endpoint doesn't resolve, it should throw a toast notification saying "The endpoint you entered doesn't resolve. Check the URL again.". The same page stays. 
2. If the endpoint resolves, then the monitor is added. There are no changes here.

**Comment by lakshmi0605** [comment]
Hi, I want to work on this issue. Can I?

**Comment by ajhollid** [comment]
> Hi, I want to work on this issue. Can I?

Most certainly! This is an open source project so please feel free to contribute!

**Comment by om-3004** [comment]
Hello @gorkem-bwl @ajhollid, please review my PR and let me know if there are any issues

**Comment by gorkem-bwl** [comment]
@om-3004 can you please make a video for this and upload here so I can check the behaviour?
