### ISSUE TITLE
Frontend Authentication 

### ISSUE THREAD

**Issue by popnfresh234** [bluewave-labs/bluewave-uptime#52]
Looks like we'll be using JWT for authentication, we should consider how we want to deal with the token on the frontend.

I think we've got two options for storing the token

1.  Cookies
2.  Local storage

Cookies are probably somewhat safer, local storage is more flexible and convenient in my experience.

We can get JWT set up on the backend and worry about frontend details when we come to it, but we can start thinking about the frontend.

**Comment by veyselboybay** [comment]
In most cases, I have used Local Storage for its convenience. Cookies are sometimes hard to work with compared to local storage.

**Comment by popnfresh234** [comment]
I also usually use local storage since we can get a javascript handle on it right away. It's vulnerable to scripting attacks, but we probably don't need to worry about that too much right now.

Sounds like local storage it is, unless the frront end folks have some strong opinions! @Skorpios604 @MuhammadKhalilzadeh please chime in if you prefer one or the other :pray:

**Comment by Skorpios604** [comment]
Ya from what I know is that local storage is vulnerable to injection attacks like XSS, but if convenience is what we are after than local storage it is.
