### ISSUE TITLE
Style Consistency

### ISSUE THREAD

**Issue by popnfresh234** [bluewave-labs/bluewave-uptime#53]
As the number of components grows it's probably worth thinking about how to maintain consistency across our library of components.

I suggest going over the frontend components before we get too far along and refactor out any common dimensions to the theme, or at least a root level CSS file.

I'm mostly thinking of values like:

* margin and padding
* font sizes
* widths/heights

I'm sure there's going to be exceptions and one off's, but I imagine there are also a large number of values that are going to be shared between many components

The sooner we get to this the less painful it will be :laughing:

**Comment by alvarotorrestx** [comment]
Hey there, can I help contribute to your project? If so, please assign me 😄

**Comment by Skorpios604** [comment]
Ya your right this is important. It already sounds painful😄

**Comment by alvarotorrestx** [comment]
Hi, I'm still willing to contribute. I'll check this out late today, thanks! 😊

**Comment by Skorpios604** [comment]
welcome @alvarotorrestx

**Comment by alvarotorrestx** [comment]
Hey everyone, thanks for your patience on allowing me to get back with you all. I've been trying to skim through everything and learn about your app while I work. I really like the code layout by the way, it's almost like we learned the same way and very similar to how I organize/code. 😅

So to my understanding, are we wanting to factor out repeating styles such as the mentioned:
- margin and padding
- font sizes
- widths/heights

And either come out with a master css file or work with the theme for reusability? 

And this is starting off with the components in the Client front end folder?
![image](https://github.com/bluewave-labs/bluewave-uptime/assets/79110517/4fb171ee-9a54-4e06-8b71-81838b7d3ec5)

Of course like mentioned, I know there will be some usage where the components will need to be manually updated on their style which makes sense. I'm just trying to get as much accurate information as I can before properly making changes/submitting PRs.

Further Notes/Questions:
- Do you all have a mockup or wireframe of how the outcome of the project?
I was able to check out the demo most components being displayed.

I have more questions on the project, but those will come over time so I don't overwhelm ya! Thanks so much! 😊

**Comment by Skorpios604** [comment]
Ya so the idea is that we have one consistent style by using MUI theme component which will customize the appearance of our application by overriding the default styles and creating a consistent look and feel. This is also good for maintainability because if values change down the line we won't have to go and change each and every one of them individually. 

Yes that is correct! So the manual ones we made an index.css file for them. 

Ya if you have anymore questions please ask.

**Comment by alvarotorrestx** [comment]
Right on, thanks for the confirmation. I'll dive into it asap 💪

**Comment by popnfresh234** [comment]
@alvarotorrestx nice to meet you!  I'd love help with documentation as well if you ever find yourself with nothing to do :stuck_out_tongue: [Issue 62](https://github.com/bluewave-labs/bluewave-uptime/issues/62) is a great place to start if you feel like tackling it.

**Comment by alvarotorrestx** [comment]
Likewise for you all! 💪

Sure I'm down for that too, documentation would be good practice for me too lol so yes if you'd like to assign me to it too 😎

**Comment by popnfresh234** [comment]
@alvarotorrestx I don't think we can assign issues to you via Github but if you'd like to work on it just go for it and make a pull request!

**Comment by alvarotorrestx** [comment]
> @alvarotorrestx I don't think we can assign issues to you via Github but if you'd like to work on it just go for it and make a pull request! 

Ahh ok got it, Thanks! 👌

**Comment by alvarotorrestx** [comment]
> Ya so the idea is that we have one consistent style by using MUI theme component which will customize the appearance of our application by overriding the default styles and creating a consistent look and feel. This is also good for maintainability because if values change down the line we won't have to go and change each and every one of them individually.
> 
> Yes that is correct! So the manual ones we made an index.css file for them.
> 
> Ya if you have anymore questions please ask.

I was able to find a lot of consistency in the styles throughout the components which I jotted down so I can start creating consistent properties or update the theme. I haven't messed too much with MUI but I can learn it, should I be updating the Theme.js in the Utils folder on the client side? Or edit the root of each stylesheet per component? I apologize in advance, I had mostly been creating with Tailwind recently.

After this I can submit something so you all can review 😊

**Comment by popnfresh234** [comment]
@alvarotorrestx no worries, we're all fairly new to MUI as well.  Tailwind is really nice, but you end up with some suuuuuuuuuuuper long class names sometimes :joy: 

`Theme.js` in utils is the root theme definition for MUI.  It would be best to add whatever values you can here, but we need to be careful about not overwriting default styles we're using elsewhere.

If you use the [theme docs for reference](https://mui.com/material-ui/customization/theming/) you should be able to stay clear of overriding things.

If it looks like there isn't an appropriate property in the theme then if you have found common values perhaps a good approach might be to use a root level CSS file.

I'm not a front end expert so I'll defer to others here, but that's my take!  Thanks again for your help here :+1:

**Comment by alvarotorrestx** [comment]
@popnfresh234 For sure, I can agree on that. I think in the end it might lead to a root level style case because there are quite a mixed amount of values. It makes sense because of what their purposes are but if there's a way to reuse, why not.

I'll start and if there's additional feedback that comes in, it can adapt. 👌
