### ISSUE TITLE
Blank notification when logging in with the wrong password. 

### ISSUE THREAD

**Issue by Skorpios604** [bluewave-labs/bluewave-uptime#616]
**To Reproduce**
Just try logging in with a wrong password. 

**Expected behavior**
There is a toast notification popping up but it is blank. Not sure if we want this here or not. 

**Screenshot**:

![no notification](https://github.com/user-attachments/assets/0524f07b-ae74-4f42-8fad-3a38f71a783c)

**Comment by gorkem-bwl** [comment]
My take is we better remove the blank notification, it is unneeded in this scenario as we provide the error message already at the right place.

**Comment by ajhollid** [comment]
Good catch, this happens if there is no response from the server, ie it is down.

```
export const login = createAsyncThunk("auth/login", async (form, thunkApi) => {
  try {
    const res = await axiosInstance.post(`/auth/login`, form);
    return res.data;
  } catch (error) {
    if (error.response && error.response.data) {
      return thunkApi.rejectWithValue(error.response.data);
    }
    return thunkApi.rejectWithValue(error.message);
  }
});
```

If there is no response we reject with `error.message.`

however the page is expecting a response in the format:

```
{
   success: false,
   msg: "error message"
   data: <data>
}
```

so we have to make sure we reject with an object of that shape :+1:
