### ISSUE TITLE
Error Handling Middleware

### ISSUE THREAD

**Issue by popnfresh234** [bluewave-labs/bluewave-uptime#64]
As the number of middleware grows, it might be nice to write an error handling middleware?

That way we can just have all the middleware throw errors instead of returing responses.  

This will allow us to have a consistent error handling process rather than dealing with errors in each middleware.

**Comment by popnfresh234** [comment]
@veyselboybay what do you think about this one?  Say we have a middleware like

```
app.use((err, req, res, next) => {
  const statusCode = err.statusCode || 500;
  logger.error(err.message, { service: error.service });
  res.status(statusCode).json({ success: false, msg: err.message });
});
```

We can pass any errors from the controllers/other middleware to the error handler:

```
try{
  ...
} catch (error) {
    error.statusCode = 404
    error.service = "Auth Service"
    next(error)
}
```
Something like that?

**Comment by veyselboybay** [comment]
This looks like a great idea and seems like the best practice. Have you got a chance to test it?

**Comment by popnfresh234** [comment]
Sure, I'll try putting it together and see how it works
