### ISSUE TITLE
Login page accessible when user is logged in

### ISSUE THREAD

**Issue by alvarotorrestx** [bluewave-labs/bluewave-uptime#641]
**Describe the bug**
I have questions on this, when a user is already logged in and they try to access the Login in page, shouldn't it redirect back to the main dashboard?

**To Reproduce**
1. Login
2. Go to /login

**Expected behavior**
Curious if you the idea is open on redirecting to the main dashboard if already logged in. 
I do see you aren't able to Sign Up if you are logged in as well.

**Comment by ajhollid** [comment]
I think this should be the desired behavior.

If a user tries to access the login page but no accounts have been registered, they should be directed to register, I believe this is working as expected.

If a user is logged in and visits login they should be directed to the main dashboard.
