### ISSUE TITLE
BE - Handling the errors/crashes during welcome mail sending

### ISSUE THREAD

**Issue by mertssmnoglu** [bluewave-labs/bluewave-uptime#691]
**Describe the bug**
When i register a new user the app is crashed because nodemailer's credentials are bad. I'm not using the Welcome Email feature, because I'm in development mode and not using it. The environment variables set to `<system_email>` and `<system_email_password>` 

In development side, I can restart the app with typing `rs` and hitting the enter but this problem will also happen in production and all of the server will getting down because of the error when sending a welcome email. Nobody wants a downtime in the uptime monitor...

**To Reproduce**
1. Set `SYSTEM_EMAIL_ADDRESS` and `SYSTEM_EMAIL_PASSWORD` environment variables to invalid credentials 
2. Register a user with `POST /api/v1/auth/register`
3. See `Invalid login Username and Password not accepted.` error from the nodemailer. Which is expected.
4. Server crash `[nodemon] app crashed - waiting for file changes before starting...`

**Expected behavior**
A log that describes the bad credential error. Users should be able to use the BlueWave Uptime Monitor even if they don't receive any welcome e-mails. 

**Screenshots**
![20240820_22h44m19s_grim](https://github.com/user-attachments/assets/bc029ef2-84c4-4c4a-ae75-68241e2864ef)

**Local Repo Informations**
 - Branch: develop
 - Fork: Yes
 - Fork Source Repo: [My Fork](https://github.com/mertssmnoglu/fork_bluewave-uptime)
 - Latest commit: fa766d259baacf63924337995d6d994fd0a1e749

**Comment by ajhollid** [comment]
I'm not sure we want the app to function without correct email credentials.  They are marked as required in the [config docs](https://github.com/bluewave-labs/bluewave-uptime?tab=readme-ov-file#env-vars-server)

We could fail gracefuly however as opposed to the hard crash that occurs right now.

**Comment by gorkem-bwl** [comment]
Just discussed this with Alex and decided the app should be running without an email server credential/configuration as well. 👍
