### ISSUE TITLE
Demo server for BlueWave Uptime

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-uptime#699]
We need a demo server which will host the latest code. It would have features as follows: 

- It has 10 different URLs that we monitor 
- It has 2 pagespeed URLs that we monitor
- Status pages section is invisible
- Integration pages section is invisible
- The account removal option is invisible
- Maintenance window settings can stay as it will eventually be implemented
- Username: demo, password: demo (prefilled if possible)

Since we have Nginx, it also can have HTTPS via Let's Encrypt as well.

I can provide the links & friendly names of those URLs if required.

**Comment by ajhollid** [comment]
Demo app deployed, username and password prefiled

- [x] Removed all account modification options from Admin users, only superadmin has access
- [x] Prefill username and password for demo user (uptimedemo@demo.com:Demouser1!)
- [x] Added 10 monitors from the JSON list
- [x] Added 2 pagespeed monitors
