### ISSUE TITLE
BE - Server side request forgery

### ISSUE THREAD

**Issue by ajhollid** [bluewave-labs/bluewave-uptime#721]
As we are allowing users to create monitors with arbitrary URLs, it is possible that they could create a monitor that points to an internal URL, allowing them to access internal resources they shouldn't be able to.

We should sanitize URLs before creating monitors to make sure that this is not possible

**Comment by gorkem-bwl** [comment]
I think this could be an option in the settings where only the admin can enable/disable for private IP addresses (eg for 10*, 172* and 192* - just examples). I don't know if a HTTPS get or ping request poses any danger on the other hand.

**Comment by ajhollid** [comment]
That's a good idea for the IP range, we should do that.

I think the issue with http requests is that the user will effectively have access to our backend to send requests on their behalf, since they control the url.

If they entered one of our endpoints as the url for example they would be able to access it as if they were the backend.

I don't think it's a huge issue atm and especially given our use case, but it's something to be aware of and come up with a mitigation strategy eventually

**Comment by gorkem-bwl** [comment]
I think that would happen if there is a network adaptor on a different internal network (e.g 192.168.0.1). We won't do it and this can be resolved, however you are right that another server hosting Uptime Manager might have this enabled, and it will then be possible to send ping/https request to internal servers, without packets going to the default router and then to the internet.

**Comment by ajhollid** [comment]
We won't worry about this one too much for now
