### ISSUE TITLE
Create routes for Checks and Alerts

### ISSUE THREAD

**Issue by popnfresh234** [bluewave-labs/bluewave-uptime#74]
We need API routes for creating Checks and Alerts.

Checks should have
 * Create
 * Read

Alerts should have
* Create
* Read
* Update

Both should have `deleteAll` routes for deleting all `Checks` and `Alerts` associated with a `Monitor`.  This will be useful for deleting or resetting a monitor

**Comment by gorkemcetin** [comment]
For the alerts, here is my take: 

- Each alert needs to have a medium (e.g email and maybe push notifications / SMS in the future)
- Each alert needs to have an email address (or phone number in case of SMS)
- The user associated with an alert should also be able to remove the alert. Maybe, the person who is setting up the alert can edit/delete that email so it never gets an alert - which can be easier.
- A monitor can have multiple alerts (e.g emails).
- Each alert needs to have a friendly name.
- Terminology: Alert contact is the person who gets an alert when an alert is generated for the corresponding monitor.
- We can separate an alert contact from an alert automation (e.g ping a Discord channel in the future when an alert is generated)
