### ISSUE TITLE
FE - Toast Position

### ISSUE THREAD

**Issue by ajhollid** [bluewave-labs/bluewave-uptime#753]
Toast notifications display over buttons in the bottom right of the screen:

![image](https://github.com/user-attachments/assets/e436fe3a-884e-4cde-92a8-9f06943277f5)

Would be nice to move the toast somewhere else where it doesnt block functional UI, maybe top right?

**Comment by gorkem-bwl** [comment]
I knew that wide open space would be useful some day!
