### ISSUE TITLE
FE - Monitor paused state

### ISSUE THREAD

**Issue by danielcj2** [bluewave-labs/bluewave-uptime#771]
Monitor should display a paused state if it's not active since it doesn't actually have a way to tell if the site is up or not.

![image](https://github.com/user-attachments/assets/d1f56fd7-ac2b-46a6-9a2a-5b7a240f1b34)

**Comment by ajhollid** [comment]
I've got an issue open for the backend side of this, #766.

@danielcj2  do you want to handle the FE side of the issue?

**Comment by danielcj2** [comment]
Aye Captain
