### ISSUE TITLE
BE - Using linters and formatters

### ISSUE THREAD

**Issue by mertssmnoglu** [bluewave-labs/bluewave-uptime#776]
## Using linters and formatters on the server side

BlueWave Uptime frontend created with vite, so it has predefined linter and formatter scripts in the `package.json` file. For example it can terminate the build stage when there is a lint error or warning and this can help developer to understand that something goes wrong.

We can also add linting and formatting tools to server side, which will positively impact the developer experience.

### My Solution

Using [biome](https://biomejs.dev/). Biome is an integrated and fast development tool chain for linting and formatting like processes. It can be easily implemented.

```shell
# Detect the problems
biome lint . 

# Detect and fix the available problems
biome lint --write . 
```
### Alternative Solutions

Biome is not the only tool, there are many solutions.

- [eslint](https://eslint.org/)
- [prettier](https://prettier.io/)

#### Additional context

- [Biome Guides](https://biomejs.dev/guides/getting-started/)

**Comment by ajhollid** [comment]
We've decided to go with Prettier due to it being time tested and the team being most familiar with it.  Thanks for your effort here though!
