### ISSUE TITLE
Cascading Delete Operations

### ISSUE THREAD

**Issue by ajhollid** [bluewave-labs/bluewave-uptime#87]
I believe Delete operation for `Monitor` should cascade to `Checks` and `Alerts`

In other words, if a user deletes a `Monitor` they created all `Checks` and `Alerts` associated with that monitor should be deleted.

**Comment by Skorpios604** [comment]
I mean that makes sense to me. No reason for the checks and alerts to remain once the monitor is gone. I think this is important for data integrity since they are all interrelated.
