### ISSUE TITLE
Create confirmation dialogs for "Clear all stats" and "Remove all monitors"

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-uptime#901]
We need two confirmation dialogs for "Clear all stats" and "Remove all monitors" buttons. Those buttons can simply say: 

- Do you want to clear all stats? [Cancel] [Yes, clear all stats]
- Do you want to remove all monitors? [Cancel] [Yes, clear all monitors]

**Comment by genial-mani** [comment]
I want to work on this could you please assign me?

**Comment by ajhollid** [comment]
> I want to work on this could you please assign me?

Hi @genial-mani ,

Sure the task is assigned to you.  Please see our codebase for examples of how we use MUI components in our project.

We'd love to have your contribution 👌

**Comment by jennifer-gan** [comment]
https://github.com/user-attachments/assets/192763a0-4fc8-476b-a498-3cf8d82de37a

@gorkem-bwl this is the video recording of the 2 dialogs for delete all monitor and remove stats feature

**Comment by gorkem-bwl** [comment]
Thanks @jennifer-gan 

One thing that caught my eye is that, when the popup appears, the screen moves to the left a bit (a few pixels). Can we remove that "shakiness"?
