### ISSUE TITLE
Fix the "current password" widget

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-uptime#907]
The "current password" section needs to be aligned.

<img width="1050" alt="Screenshot 2024-10-04 at 12 14 55 AM" src="https://github.com/user-attachments/assets/aa4c9ae8-88fb-424e-bcb7-108d115a7778">

**Comment by GaurangMapuskar** [comment]
@gorkem-bwl please assign me this issue. I will work on this immediately

**Comment by gorkem-bwl** [comment]
Sure - go ahead :)

**Comment by rishavd3v** [comment]
@gorkem-bwl is it still open? I would like to work on it.

**Comment by om-3004** [comment]
Hello @gorkem-bwl, Please find and review my PR and let me know if there are any issues.

**Comment by om-3004** [comment]
Hello @gorkem-bwl, I had some problem with the previous forked repo so I have forked a new one and created a new PR. Please find and review my PR and let me know if there are any issues.
