### ISSUE TITLE
FE - Advanced Settings Page Validation and Error Handling

### ISSUE THREAD

**Issue by ajhollid** [bluewave-labs/bluewave-uptime#913]
Currently the Advanced Settings page has no client side validation of user input and no error handling in event of invalid input.  This allows users to enter invalid input which will be rejected by server side validation.

- [ ] Add client side validation to all fields in the Advanced Settings page
- [ ] Disable submisison until all fields have valid input
- [ ] Hanlde errors in the event of invalid input

Examples of error handling can be found on any pages that have user input fields, eg Register, Login, Settings, etc

**Comment by PAVAN507-STAR** [comment]
Hii @ajhollid.I would like to work on this issue.Can you assign this issue to me?

**Comment by jennifer-gan** [comment]
I am working on this one now

**Comment by ajhollid** [comment]
@PAVAN507-STAR this issue is already assigned, thanks for your interest though :+1:

**Comment by PAVAN507-STAR** [comment]
@ajhollid Yeah my bad did'nt see it was assigned. Is there something else I can contribute to in this project

**Comment by ajhollid** [comment]
@PAVAN507-STAR no worries.

There are quite a few open issues, and more will be coming up as we keep working on the project.

We definitely need help writing tests for the back end right away and the front end eventually if you want to work on those issues.

**Comment by PAVAN507-STAR** [comment]
@ajhollid actually not knowledged enough in writing test for backend and i'll get back after i learn those things maybe by the end of this month

**Comment by jennifer-gan** [comment]
I can reuse some existing validation rules for some of the below fields in advanced settings page, however not sure about some fields:

    apiBaseUrl: "",
    logLevel: "debug",
    systemEmailHost: "",
    systemEmailPort: "",
    systemEmailAddress: "",
    systemEmailPassword: "",
    jwtTTL: "",
    dbType: "",
    redisHost: "",
    redisPort: "",
    pagespeedApiKey: "",

such as   systemEmailHost,  systemEmailPort,    jwtTTL,  dbType,    redisHost,    redisPort and  pagespeedApiKey,
other than mandatory for all, what specific rules we would like to apply to these?

**Comment by ajhollid** [comment]
@jennifer-gan you can use the `AppSettings` model as a guide for validation:

```
import mongoose from "mongoose";

const AppSettingsSchema = mongoose.Schema(
  {
    apiBaseUrl: {
      type: String,
      required: true,
      default: "http://localhost:5000/api/v1",
    },
    logLevel: {
      type: String,
      default: "debug",
      enum: ["debug", "none", "error", "warn"],
    },
    clientHost: {
      type: String,
      required: true,
      default: "http://localhost:5173",
    },
    jwtSecret: {
      type: String,
      required: true,
      default: "my_secret",
    },
    refreshTokenSecret: {
      type: String,
      required: true,
      default: "my_refresh_secret",
    },
    dbType: {
      type: String,
      required: true,
      default: "MongoDB",
    },
    dbConnectionString: {
      type: String,
      required: true,
      default: "mongodb://localhost:27017/uptime_db",
    },
    redisHost: {
      type: String,
      required: true,
      default: "127.0.0.1",
    },
    redisPort: {
      type: Number,
      default: "6379",
    },
    jwtTTL: {
      type: String,
      required: true,
      default: "2h",
    },
    refreshTokenTTL: {
      type: String,
      required: true,
      default: "7d",
    },
    pagespeedApiKey: {
      type: String,
      default: "",
    },
    systemEmailHost: {
      type: String,
      default: "smtp.gmail.com",
    },
    systemEmailPort: {
      type: Number,
      default: 465,
    },
    systemEmailAddress: {
      type: String,
      default: "",
    },
    systemEmailPassword: {
      type: String,
      default: "",
    },
    singleton: {
      type: Boolean,
      required: true,
      unique: true,
      default: true,
    },
  },
  {
    timestamps: true,
  }
);

export default mongoose.model("AppSettings", AppSettingsSchema);
```

Those settings are written to the DB using the above model, so their values should correspond
