### ISSUE TITLE
FE - Loading Spinners for data requests

### ISSUE THREAD

**Issue by ajhollid** [bluewave-labs/bluewave-uptime#914]
Currently (especially on limited bandwidth) some network requests take some time to process as sometimes a lot of data is being crunched/returned.  When this occurs a skeleton is displayed:

![image](https://github.com/user-attachments/assets/71e05af0-9d7d-4895-941b-a2252f481642)

However it isn't clear from a UI/UX point of view that a request is taking place.  It might be nice to display a loading spinner/indicator to show that a network request is taking place

**Comment by gorkem-bwl** [comment]
That is not due to the lack of CPU power right? I got two alarms today that the CPU load is over 95%.

**Comment by ajhollid** [comment]
> That is not due to the lack of CPU power right? I got two alarms today that the CPU load is over 95%.

I think partially it is, performance is worse on DO vs AWS for sure

**Comment by ajhollid** [comment]
But we need the spinners anyway just for latency

**Comment by gorkem-bwl** [comment]
Right, agreed. Maybe we can remove some of the demo servers (and leave the Uptime Manager server with only 20-30 servers to check).

**Comment by ajhollid** [comment]
> Right, agreed. Maybe we can remove some of the demo servers (and leave the Uptime Manager server with only 20-30 servers to check).

Sure, I'll make a smaller list of servers and reset it :+1:

**Comment by marcelluscaio** [comment]
@ajhollid maybe adding Tanstack Query could help with that. It provides fetch status, so we would get the loading state from there

**Comment by ajhollid** [comment]
> @ajhollid maybe adding Tanstack Query could help with that. It provides fetch status, so we would get the loading state from there

I'm not familiar with this, but I'll have a look at it, always excited about new tools!

A lot of our queries do happen through redux though so we do generally know that if a query is in progress or is successful / rejected.

**Comment by kmahesh18** [comment]
Hii @ajhollid .I would love to work on this issue.Can you assign this to me?

**Comment by ajhollid** [comment]
Hi @kmahesh18 , this issue is already assigned to a team member, thanks for your interest though :+1:

**Comment by marcelluscaio** [comment]
@ajhollid I believe we can close this issue, do you agree?

**Comment by ajhollid** [comment]
Yep, I think this one is good!
