### ISSUE TITLE
BE - Tests 

### ISSUE THREAD

**Issue by ajhollid** [bluewave-labs/bluewave-uptime#924]
Tests are needed for controllers and DB modules. Mocha and Chai are currently used for testing

**Comment by krishnateja262** [comment]
Hi @ajhollid can i contribute to this? I can try doing it for DB modules

**Comment by ajhollid** [comment]
> Hi @ajhollid can i contribute to this? I can try doing it for DB modules

Hi @krishnateja262,

Apologies I missed your request here.  Feel free to contribute tests whenver you like!
