### ISSUE TITLE
Duration shouldn't be negative

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-uptime#926]
Under Maintenance window, make sure the user shouldn't be able to enter a negative or a decimal number here.

<img width="1399" alt="Screenshot 2024-10-10 at 9 56 18 PM" src="https://github.com/user-attachments/assets/209b0f6c-9e2d-4f32-a5cb-a45a4c278afe">

**Comment by om-3004** [comment]
Hello @gorkem-bwl I would like to work on this issue. Can you assign it to me?

**Comment by gorkem-bwl** [comment]
Sure - just assigned. Thanks for your interest in the project and let us know if you have any questions.

**Comment by om-3004** [comment]
@gorkem-bwl, Please find and review my PR and let me know if there are any issues.
https://github.com/bluewave-labs/bluewave-uptime/pull/936
