### ISSUE TITLE
Add "Pause" option in the actions menu on the dashboard

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-uptime#931]
Currently, in order to pause a monitor, one should click on the monitor and then the Configure button. Adding this option to the action menu will speed it up.

<img width="1409" alt="Screenshot 2024-10-11 at 12 35 25 AM" src="https://github.com/user-attachments/assets/b31dece2-7252-4f94-9579-36dad0c9ebf0">

**Comment by Sinon11901** [comment]
I would like to work on this issue. Can you asgn this to me?

**Comment by ajhollid** [comment]
> I would like to work on this issue. Can you asgn this to me?
> 

Sure, feel free to open a pull request when you're ready, I'll be happy to take a look at it!
