### ISSUE TITLE
[Enhancement]: Light/Dark mode toggle should be in settings menu

### ISSUE THREAD

**Issue by om-3004** [bluewave-labs/bluewave-uptime#934]
The light/dark mode toggle is currently present at the user profile menu along with the log out button. Rather it should be in the settings menu under appearance.

![Screenshot 2024-10-11 113132](https://github.com/user-attachments/assets/b009914b-f1b7-40ba-9e3b-d079e885560e)

**Comment by rishavd3v** [comment]
Hey, I would like to work on this issue. It would be more intuitive and user-friendly to move it to the settings menu under "Appearance."
I'd be happy to work on this if it sounds good! Let me know your thoughts.

**Comment by ajhollid** [comment]
@om-3004 @rishavd3v

We're always open to outside contributions! Feel free to open up a pull request any time.

@gorkemcetin is our UI / UX designer so touch base with him RE design decisions and we can go from there!

**Comment by om-3004** [comment]
@gorkemcetin What do you think about this thought?

**Comment by gorkem-bwl** [comment]
> @gorkemcetin What do you think about this thought?

That makes sense. @rishavd3v are you willing to work on it?

**Comment by rishavd3v** [comment]
@gorkem-bwl yeah, would love to!

**Comment by rishavd3v** [comment]
Made a PR, @ajhollid @gorkem-bwl please review and let me know if any changes are needed.

**Comment by gorkem-bwl** [comment]
Looks good, thanks for the video.

FYI @ajhollid

**Comment by gorkem-bwl** [comment]
@rishavd3v do you think you can do a more visual design, like one of those? I can build corresponding Figma files and SVGs.

<img width="401" alt="Screenshot 2024-10-11 at 8 24 30 PM" src="https://github.com/user-attachments/assets/51d02286-1d0f-4bbf-a248-1fc695643d48">
<img width="763" alt="Screenshot 2024-10-11 at 8 25 11 PM" src="https://github.com/user-attachments/assets/2bf08637-462e-4811-8ec1-2a808a1ed36a">

**Comment by gorkem-bwl** [comment]
Another alternative is to use a React library like this one. It's simpler and easier to the eyes: https://github.com/H0rn0chse/dark-mode-toggle

**Comment by rishavd3v** [comment]
I'm still fairly new to React, so I can't commit to more visual design tasks. However, if you open up issues, I'd be happy to take a look and see if it's something I can work on. It would be a fun way for me to learn.

**Comment by gorkem-bwl** [comment]
> I'm still fairly new to React, so I can't commit to more visual design tasks. However, if you open up issues, I'd be happy to take a look and see if it's something I can work on. It would be a fun way for me to learn.

You may want to check the link above (dark-mode-toggle) and see if you can implement it, without removing the current implementation (#938). We can then try and see if it is a better looking solution.

**Comment by rishavd3v** [comment]
Got it! I’ll see if I can implement it.

**Comment by ajhollid** [comment]
> Got it! I’ll see if I can implement it.

Sounds good! 

Whenever you're ready for us to take a look at your implementation just open up a PR 👌

Please have a look at the [MUI switches](https://mui.com/material-ui/react-switch/) and other MUI components in general. 

This is the library we use to build all our UI comments so it would be ideal to use this.

**Comment by ajhollid** [comment]
@rishavd3v are you still interested in working on this?

**Comment by rishavd3v** [comment]
Hi, thanks for checking in! I’m still interested in working on this. I’ve been learning and trying to implement it. If it's urgent you can co-assign it to someone.

**Comment by ajhollid** [comment]
Not urgent, just wanted to check on the status.  Carry on, no rush!

**Comment by gorkem-bwl** [comment]
@rishavd3v wanted to check back here again if you are still interested in implementing :)
