### ISSUE TITLE
Remove photo edit button in Profile section

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-uptime#941]
We need to remove the Edit button in the Profile section. It was there for a reason, but development hasn't started, and there is no need for it. 

<img width="1403" alt="Screenshot 2024-10-11 at 3 14 54 PM" src="https://github.com/user-attachments/assets/b30548f1-1659-4396-8ff0-e3b9dc778870">

**Comment by rishavd3v** [comment]
I'm ready to work on it! Can you assign it to me?

**Comment by gorkem-bwl** [comment]
Sure, assigned. 

Are you interested in more difficult tasks by the way? I can come up with tasks on the FE side that require API calls as well.

**Comment by rishavd3v** [comment]
I can't commit to anything just yet, but feel free to open up issues. I can take a look at them and see if they align with my skills or if it's something I can tackle. Happy to contribute where I can!
