### ISSUE TITLE
Add "Docs" and "Changelog" to the main menu

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-uptime#942]
We don't have any links to our documentation on Gitbook and changelog (which is, basically, our release page). 

Here is a sample screen: 

<img width="226" alt="Screenshot 2024-10-11 at 8 40 11 PM" src="https://github.com/user-attachments/assets/c04e72e5-9bdc-4b01-9297-9536088c409a">

Here are the SVG files: 

![changelog](https://github.com/user-attachments/assets/fdcaf04a-1ff5-4de3-9b9a-c3ce599228a3)
![documents](https://github.com/user-attachments/assets/5bafd5b7-bb95-47d0-b777-b384a1a5e5df)

The design (stroke, line weight, size etc) of the SVGs must match the icons above, and none of those properties should be hard coded. 

Docs should go to https://bluewavelabs.gitbook.io/uptime-manager
Changelog should go to https://github.com/bluewave-labs/bluewave-uptime/releases

Both links should open in a new tab.

**Comment by Abhi-m-anue** [comment]
I'm ready to work on it! Can you assign it to me?

**Comment by gorkem-bwl** [comment]
Sure. Thanks for your interest.

**Comment by gorkem-bwl** [comment]
Thank you @Abhi-m-anue for the video. Looks good to me UI-wise.

**Comment by Abhi-m-anue** [comment]
I think this issue can be closed
