### ISSUE TITLE
Bug: Error handling for null email in team invite

### ISSUE THREAD

**Issue by rishavd3v** [bluewave-labs/bluewave-uptime#950]
**Description**
When the 'Send Invite' button is clicked to invite a member, the application correctly checks if the email is valid and displays an error message if it is not. However, when the email is null, the function to invite a member is called and loading animation is shown infinitely, which should not happen.

**To Reproduce**
- Navigate to Account > Team
- Click 'Invite a team member'
- Click 'Send Invite' without entering any value in email.

**Expected behavior**
If the email is null the invite function should not be triggered, and no invite should be sent.

**Screenshots**
![Screenshot (72)](https://github.com/user-attachments/assets/1851cf68-342f-452d-82c1-e9f7d11f25f6)

**Solution**
Implement a proper validation check to ensure the email is not only in the correct format but also not empty (null). The invite function should only be triggered if the email passes validation.

**Comment by rishavd3v** [comment]
I can work on this issue! Can you assign it to me?

**Comment by gorkem-bwl** [comment]
> I can work on this issue! Can you assign it to me?

Thanks for the detailed reasoning and implementation suggestion. Assigned.
