### ISSUE TITLE
Add link to logo

### ISSUE THREAD

**Issue by khd33j** [bluewave-labs/bluewave-uptime#951]
**Describe the bug**
Add the Homepage link to the logo for easier accessibility. When navigating to other pages, it would be quicker and easier to go back. 

**To Reproduce**
1. Go to the Incidents page (any page tbh)
2. Click on the logo to go back to homepage
3. Error: The logo isn't linked

**Expected behavior**
I expected to be able to navigate to the homepage in a straight-forward manner. 

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: 129.0

**Additional context**
If possible, kindly let me do this.

**Comment by Omkar2101** [comment]
Hi @khd33j
I would like to work on this issue. If it's available, could you please assign it to me?
Thank you!

**Comment by gorkem-bwl** [comment]
Thanks @khd33j - please make sure both the icon and the 'BlueWave Uptime' strings are clickable, and the user should be directed to https://github.com/bluewave-labs/bluewave-uptime on a new tab.

**Comment by khd33j** [comment]
On it! Also, could you please tag the issue with the appropriate hacktoberfest tags?

**Comment by rishavd3v** [comment]
@khd33j Repo is already tagged, your PR will be counted for hacktoberfest!

**Comment by khd33j** [comment]
Could you tell me what file I would need to work on? I can't seem to find it.

**Comment by rishavd3v** [comment]
Have a look at /Client/src/Components/Sidebar

**Comment by gorkem-bwl** [comment]
> Could anyone tell me what file I would need to work on? I can't seem to find it.

Make sure you know what you are doing. It should already be very straightforward to find where it is. Contributions are welcome provided we don't spend a lot of time with code reviews. Double check your work before committing anything for a review.

**Comment by ajhollid** [comment]
Hi @khd33j , did you still want to finish this up?  Your previous PR was pretty much done :thinking:

**Comment by khd33j** [comment]
Yea I'm done with the code. I'm having difficulty with downloading the application.

**Comment by ajhollid** [comment]
> Yea I'm done with the code. I'm having difficulty with installing the application.

Anything specific you need help getting set up?

I'd love to improve the startup directions if there's some part that's unclear

**Comment by gorkem-bwl** [comment]
@khd33j just checking back to see if you have been able to deploy it locally. Let me know please.
