### ISSUE TITLE
Not responsive

### ISSUE THREAD

**Issue by mayank-0789** [bluewave-labs/bluewave-uptime#953]
The website is not properly responsive
#screenshot
<img width="614" alt="Screenshot 2024-10-14 at 10 19 46 AM" src="https://github.com/user-attachments/assets/98077463-e7e1-4558-93f9-3965da33f411">

**Comment by mayank-0789** [comment]
hey @bluewave-labs please assign this issue to me

**Comment by ajhollid** [comment]
Hi @mayank-0789, there is already an issue open for this, #446.  This is a far reaching and in depth issue, so If you'd like to work on it please present your comprehensive proposal in #446 and we can go from there :+1: Thanks!

**Comment by ajhollid** [comment]
Hi @mayank-0789, there is already an issue open for this, #446.  This is a far reaching and in depth issue, so If you'd like to work on it please present your comprehensive proposal in #446 and we can go from there :+1: Thanks!
