### ISSUE TITLE
Incidents, maintenance and team table header fix

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-uptime#963]
The incidents, maintenance and team table header should look like the table header on the main dashboard. Double check the style, font size, weight and color.

This is the incidents table header: 

<img width="1102" alt="image" src="https://github.com/user-attachments/assets/1d9e20af-b08d-481e-adf2-6849ae0a73e3">

This is the maintenance table header:

<img width="1095" alt="image" src="https://github.com/user-attachments/assets/42846cee-4f9a-40fa-8a18-63b2d2e41c40">

This is the Teams table header:
<img width="1018" alt="image" src="https://github.com/user-attachments/assets/f5aea3cf-6062-4924-8f36-9a2c7bbd2856">

This is the table header on the dashboard. All previous 3 table headers should look like this.

<img width="1052" alt="image" src="https://github.com/user-attachments/assets/b0403ab3-c343-4887-9003-aa4cd931b954">

**Comment by rishavd3v** [comment]
Can I work on this issue?

**Comment by gorkem-bwl** [comment]
Please go ahead.

**Comment by rishavd3v** [comment]
Created a PR #974. Have a look.
