### ISSUE TITLE
About page should also show the latest version on GitHub

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-uptime#967]
When the user goes to Settings page, the About block should show the latest version number pulled from GitHub.

This is currently how it looks:

<img width="1129" alt="image" src="https://github.com/user-attachments/assets/60933191-9b99-47df-a34c-ad7d1165ef37">

This is how it should look like (ignore the Figma design - use the current styling):

<img width="892" alt="image" src="https://github.com/user-attachments/assets/7de017c6-ce28-4c1d-8a05-7f15e42cac7e">

**Comment by navishmonga** [comment]
Can I work on this issue please ?

**Comment by PDGamerSG** [comment]
Can I work on this issue please ?

**Comment by Celnet-hub** [comment]
I have a question to ask. is the version number just after BlueWave Uptime not supposed to be the latest version? Adding about version label seems redundant in my opinion. What do you think @gorkem-bwl

**Comment by gorkem-bwl** [comment]
> I have a question to ask. is the version number just after BlueWave Uptime not supposed to be the latest version? Adding about version label seems redundant in my opinion. What do you think @gorkem-bwl

For example, an admin may be deploying the latest version, however one month later it may be an old version already if there is another version on GitHub. Am I missing something here?
