### ISSUE TITLE
Unexpected Redirection to Login in withAdminCheck Higher-Order Component (HOC)

### ISSUE THREAD

**Issue by lakshyeahh** [bluewave-labs/bluewave-uptime#984]
**Describe the bug**
Users are being redirected to the /login route even when a super admin already exists. This behavior appears inconsistent with the intended logic. The issue seems related to the condition inside the withAdminCheck HOC, potentially causing incorrect redirections based on the API response from networkService.doesSuperAdminExist().

**To Reproduce**
1. Wrap any React component using the withAdminCheck HOC:
`
const AdminPage = withAdminCheck(SomeComponent);
export default AdminPage;
`
2. Run the application.
3. Access the wrapped component.
4. Observe: The user is redirected to /login, even if a super admin exists.

**Expected behavior**
If a super admin exists (API returns true), the wrapped component should render normally.
If a super admin does not exist (API returns false), users should be redirected to /login.

**Actual behavior**
The wrapped component always redirects to /login even when the response from the API indicates that the super admin exists (response.data.data === true).

https://github.com/user-attachments/assets/e51d1837-91e4-4c37-8415-e727d75815b7

**Desktop (please complete the following information):**
 - Browser: Google Chrome
 - Version: 129.0.6668.101

**Suspected Cause**:
Logic Error:
The condition if (response.data.data === true) causes a redirect to /login when a super admin exists.
This seems opposite to the expected logic, where the component should render when a super admin exists.
API Response Mismatch:

The field response.data.data might not correctly reflect the existence of a super admin. A different field or structure could be expected.

**Comment by ajhollid** [comment]
> **Describe the bug**
> Users are being redirected to the /login route even when a super admin already exists. This behavior appears inconsistent with the intended logic. The issue seems related to the condition inside the withAdminCheck HOC, potentially causing incorrect redirections based on the API response from networkService.doesSuperAdminExist().
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Wrap any React component using the withAdminCheck HOC:
> `
> const AdminPage = withAdminCheck(SomeComponent);
> export default AdminPage;
> `
> 2. Run the application.
> 3. Access the wrapped component.
> 4. Observe: The user is redirected to /login, even if a super admin exists.
> 
> **Expected behavior**
> If a super admin exists (API returns true), the wrapped component should render normally.
> If a super admin does not exist (API returns false), users should be redirected to /login.
> 
> **Actual behavior**
> The wrapped component always redirects to /login even when the response from the API indicates that the super admin exists (response.data.data === true).
> 
> https://github.com/user-attachments/assets/e51d1837-91e4-4c37-8415-e727d75815b7
> 
> 
> 
> **Desktop (please complete the following information):**
>  - Browser: Google Chrome
>  - Version: 129.0.6668.101
> 
> **Suspected Cause**:
> Logic Error:
> The condition if (response.data.data === true) causes a redirect to /login when a super admin exists.
> This seems opposite to the expected logic, where the component should render when a super admin exists.
> API Response Mismatch:
> 
> The field response.data.data might not correctly reflect the existence of a super admin. A different field or structure could be expected.
> 

Hi @lakshyeahh ,

I believe this is the intended behavior. 

The registration screen should only be shown once for the initial creation of the first user, the super admin. 

All further accounts are created by email invitation only.

**Comment by lakshyeahh** [comment]
Thank you for the clarification! I understand now that the behavior is intentional, with the registration screen shown only for the initial super admin creation.
Is there any on going or future issue you would like me to work on.

**Comment by gorkem-bwl** [comment]
@lakshyeahh what kind of issues would like to work on? Let me know your past experience & capabilities so I can guide you.

**Comment by lakshyeahh** [comment]
I have great experience in forntend, js, ts, bug fixing, trouble shooting, ui enhancement, feature testing

**Comment by gorkem-bwl** [comment]
@lakshyeahh please check this one.
