### ISSUE TITLE
BE - Hardware Monitoring Integration

### ISSUE THREAD

**Issue by ajhollid** [bluewave-labs/bluewave-uptime#985]
The BE needs to be prepared to integrate with the [hardware monitoring agent](https://github.com/mertssmnoglu/bluewave-uptime-agent) being developed by @mertssmnoglu 

- [x] Design and implement database models
  - [x] Use JSON model from @mertssmnoglu  
- [x] Design and Implement DB methods
- [x] Update NetworkService to handle Hardware monitor types

**Comment by mertssmnoglu** [comment]
Work in Progress on [Hardware Monitoring Agent](https://github.com/mertssmnoglu/bluewave-uptime-agent)

**Comment by gorkem-bwl** [comment]
Looks good. Can we also send the distro_name, OS and kernel_version alongside with those properties you have in your repo @mertssmnoglu ?

**Comment by mertssmnoglu** [comment]
I'm updating the Agent's API Responses you can check the repo [here](https://github.com/mertssmnoglu/bluewave-uptime-agent)

Memory metrics are done for Linux, but I want to ask you about memory usage percentage response. Which response is more usable/effective for both frontend and backend?

```json
"memory": {
  ...
  "usage_percent": 0.417053
}
```
```json
"memory": {
  ...
  "usage_percent": 41.7053
}
```

**Comment by gorkem-bwl** [comment]
While the backend can take care of both, for the sake of human readability, I would say the second one is more appropriate. You can even leave a single digit after the dot.

**Comment by ajhollid** [comment]
> While the backend can take care of both, for the sake of human readability, I would say the second one is more appropriate. You can even leave a single digit after the dot.

@mertssmnoglu @gorkem-bwl we use decimal format elsewhere in the BE (0.4325 instead of 43.25) so if it's no big deal it would be nice to keep that consistently on the BE.

FE we will definitely display a user friendly format.

**Comment by gorkem-bwl** [comment]
> > While the backend can take care of both, for the sake of human readability, I would say the second one is more appropriate. You can even leave a single digit after the dot.
> 
> @mertssmnoglu @gorkem-bwl we use decimal format elsewhere in the BE (0.4325 instead of 43.25) so if it's no big deal it would be nice to keep that consistently on the BE.
> 
> FE we will definitely display a user friendly format.

Lol I jumped in too soon :-D

**Comment by ajhollid** [comment]
BE implemenation is complete
